### ISSUE TITLE
BUG: Settings not persistent when changed via thin client

### ISSUE THREAD

**Issue by seanvree** [levic92/LCExtractor#3]
Hey @levic92 , 

There's some type of bug where the settings for the plug-in aren't sticking after you make changes to the server via the thin client.  If I make the changes ON the box that is hosting deluged-debug via the GTK UI, hit apply, exit the thin client (so the servcie is still running), and then re-launch the thin-client, the plug-in is still enabled, but all settings are default.  What is weird, is that the functionaly is still working....so it MAY just be a UI thing?!

I'm not sure how you've tested this. This MIGHT be my particular environment.   However, I did test on two diff windows hosts, and the issue was present on both.  

- I run deluged-debug.exe as a windows servcie (system) vis NSSM.
- I use deluge.exe thin client to manage from either another box on my LAN or the actual host running deluged-debug.

Not sure if you have the tools to reproduce, but if not, I can do a  teamviewer so I can show you, but it's def there. 

LMK.

**Comment by levic92** [comment]
I was having the same issue. It was happening to this plugin but also others I was testing. I would lose the setting on a restart of Deluge. I think its a bug in deluge. I just manually edited the conf files to the state I wanted and I haven't had any issues since.

**Comment by seanvree** [comment]
@levic92  yeah, it only happens on this plug-in for me.

**Comment by nenladar** [comment]
I've seen a variant of this: the settings persist, but if I re-open preferences and change something entirely unrelated (e.g. Bandwidth settings), the plugin's settings get re-saved incorrectly.

If I go to the deluge config directory on my server, I can see that lcextractor.conf was changed at the same time that core.conf was, and the difference was exactly re-setting the flags which were added since the original Extractor fork:

```
$ diff lcextractor.conf lcextractor.conf~
5,7c5,7
<   "use_name_folder": true, 
<   "in_place_extraction": true, 
<   "sonarr_radarr_support": true, 
---
>   "use_name_folder": false, 
>   "in_place_extraction": false, 
>   "sonarr_radarr_support": false, 
```

**Comment by nenladar** [comment]
Okay, I think I see another symptom of the bug: if I open preferences, and just re-apply them, then lcextractor.conf ends up with two copies of the config in the same file, one of which is "correct", the other which is the 'reset' one:

```
$ cat lcextractor.conf*
{
  "file": 1, 
  "format": 1
}{
  "use_name_folder": true, 
  "in_place_extraction": true, 
  "sonarr_radarr_support": true, 
  "extract_path": "/volume1/media/incoming/inprogress"
}{
  "file": 1, 
  "format": 1
}{
  "use_name_folder": false, 
  "in_place_extraction": false, 
  "sonarr_radarr_support": false, 
  "extract_path": "/volume1/media/incoming/inprogress"
}
```

**Comment by nenladar** [comment]
This ticket looks likely related, since it's for the original Extractor plugin, though there's no additional information currently: http://dev.deluge-torrent.org/ticket/2929

**Comment by nenladar** [comment]
I believe the problem is in data/lcextractor.js. The fields of the webui are populated when updateConfig is called, but updateConfig is only called when the preference pane is shown, due to `        this.on('show', this.updateConfig, this);`.

So if the preference pane was not shown, the config will never have been loaded, but the `onOk` and `onApply` triggers will still occur, saving the uninitialized values. This appears to also hold true for the `Scheduler` default plugin.

I think we need something roughly equivalent to what the core preferences window does, e.g.:

https://github.com/deluge-torrent/deluge/blob/72c588ad3331ea4be0fed75000d73e7e4abe2903/deluge/ui/web/js/deluge-all/preferences/PreferencesWindow.js#L109

...in which it only conditionally does the set_config call, if something changed.

**Comment by theCheek** [comment]
This bug is entirely the reason why I've switched over from the simple extractor plugin to this one. Ever now and then I would find that the config of simple extractor would reset to default, resulting in extractions happening in the base directory of my seedbox and not 'in place' as is preferred for sonarr/radarr to work. 

I think its a general Deluge bug because it has been present in every extractor plugin i've tested on Deluge.  Perhaps the commit above this comment will fix it, if not then perhaps making the .conf file read only after setting the desired preferences may be a (dirty) workaround?

**Comment by Anthirian** [comment]
I've marked the file as readonly but that did not seem to work properly. In addition I changed its owner and group to root, so deluge can only read it now even though it has write permissions in the config directory. Previously I think it would be overwritten with a new file and therefore the readonly failed. Hope this fix gets pushed soon so I can revert this workaround.

**Comment by levic92** [comment]
The way I got around this bug was to manually edit the conf file and not use the GUI. I thought it was a deluge bug, but there is currently a pull request to fix this issue with the extraction plugin code. I will test it this weekend and then merge it if it fixes the issue.

**Comment by QuickShotx** [comment]
For what it's worth, I copy and pasted the changes and compiled 3-4 weeks ago and i haven't had any issues with the settings reverting. 

Seems to have fixed the problem for me.

**Comment by levic92** [comment]
So first can you double check on the Plugins page that LCExtractor is v0.6.2?

I have deluge installed on linux and use the web ui and this is working. I spent considerably more time testing this than expected, this is partially because the deluge UI is so buggy. I started testing by installing deluge on windows and using the default GUI but that thing had so many issues I couldn't reproduce the problem because there were so many bugs. Next I decided just to try the web ui and I was able to reproduce the problem using the old version of LCExtractor. Once I installed the new version the problem was fixed in the web ui.

Is there any reason you aren't using the web ui?

**Comment by nenladar** [comment]
For what it's worth, I found during my original testing that the old
version of the plug-in still had remnants cached, namely the offending .js
file. Once I nuked that, the correct value was extracted from the plug-in.

It might be worth inserting the plug-in version into the UI panel,
hard-coded in the .js, just to make it easier to discover this type of
mismatch.

**Comment by seanvree** [comment]
@levic92  okay, yeah, just testes.  It works on the WebUI not in the Thin Client. I usually use the thin client because I have a local seedbox on my LAN, so obviously, the thin Client is much easier to use.  

Thanks brotha.
